name: BGMI Attack Bot

on:
  workflow_dispatch:
    inputs:
      target_ip:
        description: 'Target IP'
        required: true
      target_port:
        description: 'Port'
        required: true
        default: '27015'
      duration:
        description: 'Duration (sec)'
        required: true
        default: '60'

jobs:
  bot-runner:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runner_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pyTelegramBotAPI pymongo certifi

      - name: Run Bot
        env:
          RUNNER_ID: ${{ matrix.runner_id }}
          BOT_TOKENS: ${{ secrets.BOT_TOKENS }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
        run: python telegram_attack_bot_v2.py
